import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  bool _isVietnamese = true;

  bool get isVietnamese => _isVietnamese;

  void toggleLanguage() {
    _isVietnamese = !_isVietnamese;
    notifyListeners(); // Báo cho toàn bộ app biết ngôn ngữ đã đổi
  }

  // Từ điểm song ngữ
  String getText(String key) {
    if (_isVietnamese) {
      return _vietnamese[key] ?? key;
    } else {
      return _english[key] ?? key;
    }
  }

  static final Map<String, String> _vietnamese = {
    'app_name': 'DanaNet',
    'ask_ai': 'Hỏi trợ lý AI',
    'tree_grew': 'Cây đã lớn thêm! 🌱 ➔ 🌿',
    'need_water': 'Cần 20 💧 để tưới.',
    'reset_title': 'Tái sinh cây? ♻️',
    'reset_content': 'Bạn có muốn trồng lại cây mới?',
    'cancel': 'Huỷ',
    'confirm': 'Đồng ý',
    'max_level_title': 'Cây Đã Đạt Đỉnh! 👑',
    'great': 'Tuyệt vời',
    'default_result': 'Hãy chụp ảnh để Server phân loại',
    'uploading': 'Đang gửi ảnh lên Server...',
    'result_prefix': 'Kết quả:',
    'confidence': 'Độ tin cậy:',
    'server_error': 'Lỗi Server:',
    'connection_error': 'Lỗi kết nối Server',
    'understood': 'Đã hiểu',
    'analysis_result': 'Kết quả phân tích',
    'unknown': 'Không rõ',
    'profile': 'Thông tin cá nhân',
    'dark_mode': 'Chế độ tối (Dark Mode)',
    'report_trash': 'Gửi báo cáo rác',
    'report_history': 'Lịch sử báo cáo',
    'forum': 'Diễn đàn Ve chai',
    'redeem_points': 'Đổi Điểm Thưởng',
    'feedback': 'Gửi đánh giá',
    'about_app': 'Thông tin ứng dụng',
    'change_password': 'Đổi mật khẩu',
    'logout': 'Đăng xuất',
    'logout_confirm_title': 'Đăng xuất',
    'logout_confirm_msg': 'Bạn có chắc chắn muốn đăng xuất?',
    'current_password': 'Mật khẩu hiện tại',
    'new_password': 'Mật khẩu mới',
    'confirm_new_password': 'Xác nhận mật khẩu mới',
    'forgot_password_q': 'Quên mật khẩu hiện tại?',
    'save_changes': 'Lưu thay đổi',
    'enter_old_pass': 'Vui lòng nhập mật khẩu cũ',
    'pass_min_len': 'Mật khẩu phải trên 6 ký tự',
    'pass_not_match': 'Mật khẩu không khớp',
    'pass_change_success': 'Đổi mật khẩu thành công!',
    'email_sent': 'Đã gửi email đặt lại mật khẩu đến',
    'error': 'Lỗi',
    'ai_scan_title': 'Phân loại rác bằng AI (Server)',
    'sending_server': 'Đang gửi Server...',
    'take_trash_photo': 'Chụp ảnh rác thải',
    'camera': 'Chụp ảnh',
    'gallery': 'Thư viện',
    'your_garden': 'Vườn cây của bạn',
    'level_max': 'Cấp độ: MAX 👑',
    'level': 'Cấp độ:',
    'rebirth_tree': 'Tái sinh cây',
    'water_tree': 'Tưới cây (-20💧)',
    'ai_bot_name': 'Trợ lý BlueBot',
    'ai_input_hint': 'Bạn vui lòng nhập câu hỏi nhé',
    'ai_system_busy':
        'Tất cả các hệ thống đều đang bận hoặc quá tải. Bạn vui lòng quay lại sau ít phút nhé!',
    'ai_persona':
        'Bạn là một chuyên gia về môi trường và xử lý rác thải tên là BlueBot. Nhiệm vụ của bạn là hướng dẫn người dùng cách phân loại rác, tái chế rác và xử lý rác nguy hại. Hãy trả lời ngắn gọn, thân thiện, dùng biểu tượng cảm xúc (emoji). Nếu người dùng hỏi vấn đề không liên quan đến rác hay môi trường, hãy từ chối khéo léo.',
    'ai_greeting':
        'Xin chào! 🌊 Tôi là BlueBot. Bạn đang băn khoăn không biết vứt rác này ở đâu? Hãy hỏi tôi nhé!',
    'profile_title': 'Hồ Sơ Cá Nhân',
    'verified': 'Đã xác thực',
    'pending_approval': 'Đang chờ duyệt',
    'verify_now': 'Xác thực ngay (Chưa verified)',
    'basic_info': 'Thông tin cơ bản',
    'full_name': 'Họ và Tên',
    'enter_name': 'Nhập tên',
    'email': 'Email',
    'phone_number': 'Số điện thoại',
    'activity_address': 'Địa chỉ hoạt động',
    'search_help': 'Hỗ trợ tìm kiếm theo Tỉnh/Huyện/Xã',
    'province_city': 'Tỉnh/Thành phố',
    'district': 'Quận/Huyện',
    'ward': 'Phường/Xã',
    'street_name': 'Số nhà, Tên đường',
    'enter_street': 'Vui lòng nhập số nhà/đường',
    'select_province': 'Vui lòng chọn Tỉnh/TP',
    'select_district': 'Vui lòng chọn Quận/Huyện',
    'select_ward': 'Vui lòng chọn Phường/Xã',
    'kyc_title': 'Xác thực danh tính (eKYC)',
    'kyc_desc': 'Vui lòng tải lên ảnh CCCD để xác minh',
    'front_card': 'Mặt trước',
    'back_card': 'Mặt sau',
    'send_request': 'GỬI YÊU CẦU',
    'take_photo': 'Chụp ảnh',
    'choose_gallery': 'Chọn ảnh từ thư viện',
    'update_success': 'Cập nhật thành công!',
    'report_title': 'Báo Cáo Điểm Rác',
    'scene_image': '1. Hình ảnh hiện trường:',
    'tap_to_capture': 'Nhấn để chụp ảnh',
    'ai_checking': 'AI đang kiểm tra độ đầy...',
    'ai_assessment': 'Đánh giá từ AI:',
    'location_section': '2. Địa điểm:',
    'search_province': 'Nhập tên Tỉnh/Thành',
    'search_district': 'Nhập tên Quận/Huyện',
    'search_ward': 'Nhập tên Xã/Phường',
    'street_hint': 'Số nhà, tên đường',
    'content_section': '3. Nội dung:',
    'desc_hint': 'Mô tả',
    'emergency_report': 'BÁO CÁO KHẨN CẤP',
    'send_report': 'GỬI BÁO CÁO',
    'fill_info_alert': 'Vui lòng điền đủ thông tin!',
    'report_success': 'Gửi báo cáo thành công!',
    'ai_error_overload':
        'Hệ thống đang quá tải. Vui lòng thử lại sau hoặc nhập mô tả thủ công',
    'ai_error': 'Lỗi xử lý ảnh',
    'ai_prompt': 'Hãy đóng vai trợ lý môi trường. Nhìn ảnh và nhận xét ngắn gọn cho người dùng:\n'
        '- Đây là vật thể gì? (Thùng rác, bãi rác hay vật khác?)\n'
        '- Tình trạng vệ sinh thế nào? (Sạch sẽ, bừa bãi, hay rác đầy tràn?)\n'
        'Kết thúc câu trả lời, BẮT BUỘC ghi kết luận trong ngoặc vuông: [BÌNH THƯỜNG] hoặc [KHẨN CẤP] (Chỉ chọn Khẩn cấp nếu là thùng rác đầy >90% hoặc rác vứt bừa bãi gây ô nhiễm).\n'
        'Ví dụ trả lời mong muốn: "Đây chỉ là một chiếc ghế gỗ, không phải nơi tập kết rác. Khu vực này sạch sẽ. [BÌNH THƯỜNG]"',
    'history_title': 'Lịch sử báo cáo',
    'login_required': 'Vui lòng đăng nhập',
    'load_err': 'Lỗi tải dữ liệu',
    'no_reports': 'Bạn chưa gửi báo cáo nào.',
    'processed': 'ĐÃ XỬ LÝ',
    'pending': 'ĐANG CHỜ',
    'edit': 'Sửa',
    'delete': 'Xóa',
    'confirm_delete': 'Xác nhận xóa',
    'delete_msg': 'Bạn có chắc muốn xóa báo cáo này không?',
    'deleted': 'Đã xóa báo cáo',
    'delete_err': 'Lỗi xóa',
    'update_info': 'Cập nhật thông tin',
    'content_desc': 'Nội dung mô tả',
    'enter_new_content': 'Nhập nội dung mới',
    'please_fill': 'Vui lòng không để trống thông tin',
    'update_err': 'Lỗi cập nhật',
    'redeem_title': 'Đổi Quà & Voucher',
    'your_points': 'Điểm tích lũy của bạn',
    'earn_points_hint': 'Hãy bán ve chai để nhận điểm!',
    'no_rewards': 'Chưa có quà tặng nào',
    'gift_default': 'Quà tặng',
    'points': 'điểm',
    'redeem_now_btn': 'ĐỔI QUÀ NGAY',
    'not_enough_points_btn': 'KHÔNG ĐỦ ĐIỂM',
    'not_enough_points_msg': 'Bạn không đủ điểm!',
    'confirm_redeem': 'Xác nhận đổi quà',
    'redeem_ask_1': 'Bạn muốn dùng',
    'redeem_ask_2': 'điểm để đổi',
    'redeem_now': 'Đổi ngay',
    'insufficient_points_err':
        'Điểm không đủ (có thể đã bị thay đổi ở nơi khác)',
    'redeem_success_title': 'Đổi quà thành công!',
    'redeem_success_msg_1': 'Bạn đã đổi thành công',
    'redeem_success_msg_2': 'Đổi thành công',
    'support_info_title': 'Thông tin hỗ trợ',
    'important_note': 'Lưu ý quan trọng:',
    'support_desc':
        'Nếu trong 2-3 ngày bạn chưa nhận được quà, vui lòng liên hệ:\n\n📞 Hotline: 0907160203\n🏠 Địa chỉ: K55/28 Ngũ Hành Sơn, Đà Nẵng\n\nđể được hỗ trợ ngay lập tức bạn nhé!',
    'sync_success': 'Đã đồng bộ! Điểm thực tế là:',
    'sync_error': 'Lỗi đồng bộ:',
    'feedback_title': 'Gửi Đánh Giá & Góp Ý',
    'enter_feedback_err': 'Vui lòng nhập nội dung góp ý!',
    'anonymous': 'Ẩn danh',
    'feedback_success': 'Cảm ơn bạn đã gửi đánh giá!',
    'how_feel': 'Bạn cảm thấy ứng dụng thế nào?',
    'rate_hint': 'Chọn số sao để đánh giá',
    'feedback_content': 'Nội dung góp ý:',
    'feedback_hint_text':
        'Hãy chia sẻ ý kiến của bạn để chúng tôi cải thiện tốt hơn nhé',
    'send_feedback_btn': 'GỬI ĐÁNH GIÁ',
    'app_version': 'Phiên bản',
    'intro_header': '📖 Giới thiệu',
    'intro_content':
        'DanaNet là ứng dụng kết nối cộng đồng nhằm thúc đẩy việc phân loại rác thải và bảo vệ môi trường. \n\nChúng tôi giúp người có phế liệu (ve chai) kết nối dễ dàng với người thu mua, đồng thời tích điểm đổi quà hấp dẫn.',
    'usage_header': '🚀 Cách sử dụng',
    'step1_title': 'Đăng tin bán ve chai',
    'step1_desc': 'Chụp ảnh, nhập thông tin và chọn vị trí của bạn',
    'step2_title': 'AI Phân tích',
    'step2_desc': 'Hệ thống AI sẽ hỗ trợ nhận diện loại rác thải',
    'step3_title': 'Giao dịch & Quét mã',
    'step3_desc': 'Gặp người mua, quét mã QR để xác nhận giao dịch',
    'step4_title': 'Tích điểm & Đổi quà',
    'step4_desc': 'Nhận điểm thưởng và đổi lấy voucher hoặc quà tặng',
    'dev_team': '💻 Đội ngũ phát triển',
    'dev_role': 'Lập trình viên & Sáng lập',
    'copyright': '© 2025 Dự án DanaNet bởi Nguyễn Kỳ Nam',
    'app_welcome': 'DANANET XIN CHÀO',
    'app_slogan': 'Cùng chung tay bảo vệ môi trường',
    'login_title': 'ĐĂNG NHẬP',
    'register_title': 'ĐĂNG KÝ TÀI KHOẢN',
    'email_or_phone': 'Email hoặc Số điện thoại',
    'password': 'Mật khẩu',
    'otp_hint': 'Hệ thống sẽ gửi mã OTP xác thực',
    'forgot_password': 'Quên mật khẩu?',
    'register_now': 'ĐĂNG KÝ NGAY',
    'send_otp': 'GỬI MÃ OTP',
    'login_now': 'ĐĂNG NHẬP',
    'have_account': 'Đã có tài khoản? Quay lại Đăng nhập',
    'no_account': 'Chưa có tài khoản? Đăng ký Email',
    'enter_name_err': 'Vui lòng nhập Họ và Tên!',
    'enter_email_phone_err': 'Vui lòng nhập Email hoặc Số điện thoại!',
    'enter_pass_err': 'Vui lòng nhập Mật khẩu!',
    'register_success': 'Đăng ký thành công! Đang vào hệ thống...',
    'register_err': 'Lỗi đăng ký:',
    'login_fail': 'Đăng nhập thất bại',
    'user_not_found': 'Tài khoản không tồn tại',
    'wrong_password': 'Sai mật khẩu',
    'invalid_phone': 'Số điện thoại không hợp lệ',
    'auth_error': 'Lỗi xác thực',
    'otp_dialog_title': 'Nhập mã OTP',
    'otp_sent_msg': 'Mã xác thực đã gửi đến điện thoại',
    'otp_incorrect': 'Mã OTP không đúng!',
    'new_user': 'Người dùng mới',
    'account_locked': 'Tài khoản đã bị khóa!',
    'enter_email_reset': 'Vui lòng nhập Email để lấy lại mật khẩu',
    'reset_email_sent': 'Đã gửi email khôi phục mật khẩu!',
    'email_not_found': 'Lỗi: Không tìm thấy email hoặc định dạng sai',
    'create_post_title': 'Đăng Tin Mới',
    'edit_post_title': 'Chỉnh Sửa Tin',
    'forum_rule_info':
        'Diễn đàn chỉ dành cho việc mua bán ve chai, phế liệu và rác tái chế',
    'i_want_sell': 'Tôi muốn bán',
    'i_want_buy': 'Tôi muốn mua',
    'take_photo_required': 'Chụp ảnh (Bắt buộc)',
    'take_photo_optional': 'Chụp ảnh (Tùy chọn)',
    'waste_type_label': 'Loại phế liệu',
    'post_title_label': 'Tiêu đề',
    'enter_title_err': 'Cần nhập tiêu đề',
    'post_desc_label': 'Mô tả chi tiết tình trạng',
    'address_contact_header': 'Địa chỉ & Liên hệ',
    'contact_phone': 'SĐT liên hệ',
    'enter_phone_err': 'Cần nhập SĐT',
    'policy_pledge':
        'Tôi cam kết bài đăng này đúng chủ đề và chịu trách nhiệm về thông tin',
    'post_now_btn': 'ĐĂNG TIN NGAY',
    'update_post_btn': 'CẬP NHẬT TIN',
    'full_address_err': 'Vui lòng chọn đầy đủ địa chỉ!',
    'seller_image_err': 'Người bán vui lòng có ảnh sản phẩm!',
    'policy_err': 'Vui lòng đồng ý với chính sách!',
    'post_success': 'Đăng tin thành công!',
    'post_update_success': 'Cập nhật tin thành công!',
    'type_paper': 'Giấy & Bìa',
    'type_plastic': 'Nhựa tái chế',
    'type_metal': 'Kim loại (Sắt/Nhôm)',
    'type_electronic': 'Đồ điện tử cũ',
    'type_glass': 'Thủy tinh',
    'type_other': 'Phế liệu khác',
    'anonymous_user': 'Ẩn danh',
    'other_waste': 'Khác',
    'buy_prefix': 'Mua: ',
    'sell_prefix': 'Bán: ',
    'just_now': 'Vừa xong',
    'recently': 'Mới đây',
    'no_address': 'Không có địa chỉ',
    'transaction_completed': 'ĐÃ GIAO DỊCH',
    'forum_title': 'Chợ Ve Chai Online',
    'filter_area': 'Lọc theo khu vực',
    'clear_filter': 'Xóa bộ lọc',
    'apply': 'Áp dụng',
    'area_label': 'Khu vực:',
    'filter_all': 'Tất cả',
    'filter_seller': 'Người Bán',
    'filter_buyer': 'Người Mua',
    'post_btn': 'Đăng Tin',
    'no_posts': 'Chưa có bài đăng nào',
    'no_posts_match': 'Không tìm thấy bài đăng phù hợp',
    'post_detail_title': 'Chi Tiết Tin',
    'enable_gps_err': 'Vui lòng bật định vị (GPS) để tiếp tục',
    'gps_denied_err': 'Quyền truy cập vị trí bị từ chối',
    'gps_permanent_denied_err':
        'Quyền vị trí bị chặn vĩnh viễn. Hãy mở cài đặt để cấp quyền',
    'transaction_success_msg':
        'Giao dịch thành công! Điểm tích lũy đã được cộng',
    'qr_auth_title': 'Mã xác thực giao dịch',
    'qr_instruction':
        'Đưa mã này cho Người Mua quét.\nKhoảng cách tối đa cho phép: 15m',
    'waiting_buyer_scan': 'Đang chờ người mua quét...',
    'undo_title': 'Hoàn tác giao dịch?',
    'undo_msg': 'Điểm thưởng đã nhận sẽ bị thu hồi. Bạn có chắc chắn không?',
    'agree_undo': 'Đồng ý Hoàn tác',
    'undo_success': 'Đã hoàn tác và thu hồi điểm thưởng.',
    'report_post_title': 'Báo cáo bài viết',
    'select_reason_label': 'Hãy chọn lý do báo cáo:',
    'report_detail_hint': 'Chi tiết thêm (Tùy chọn)',
    'send_report_btn': 'Gửi Báo Cáo',
    'report_thank_you': 'Đã gửi báo cáo. Cảm ơn bạn!',
    'login_to_report': 'Vui lòng đăng nhập để báo cáo!',
    'delete_post_confirm': 'Xóa bài viết?',
    'action_cannot_undo': 'Hành động này không thể hoàn tác',
    'delete_post_success': 'Đã xóa bài viết',
    'post_deleted_or_missing': 'Bài viết không còn tồn tại',
    'undo_transaction_btn': 'HOÀN TÁC GIAO DỊCH',
    'show_qr_btn': 'HIỆN MÃ QR GIAO DỊCH',
    'call_btn': 'GỌI',
    'scan_qr_btn': 'QUÉT MÃ',
    'transaction_done_btn': 'ĐÃ GIAO DỊCH',
    'edit_post_menu': 'Chỉnh sửa',
    'delete_post_menu': 'Xóa bài',
    'report_violation_menu': 'Báo cáo vi phạm',
    'image_error': 'Lỗi ảnh',
    'transaction_completed_banner': 'GIAO DỊCH HOÀN TẤT',
    'want_to_sell_tag': 'Cần Bán',
    'want_to_buy_tag': 'Cần Mua',
    'description_header': 'Mô tả chi tiết:',
    'no_description': 'Không có mô tả',
    'reason_scam': 'Lừa đảo',
    'reason_prohibited': 'Hàng cấm/Sai quy định',
    'reason_spam': 'Spam/Quảng cáo',
    'reason_hate': 'Ngôn từ thù ghét',
    'reason_other': 'Khác',
    'scan_confirm_title': 'Quét mã xác nhận',
    'qr_invalid': 'Mã QR không hợp lệ',
    'qr_missing_info': 'Mã QR thiếu thông tin cần thiết',
    'qr_wrong_post':
        'Sai mã QR!\nBạn đang xem bài viết khác với mã QR được quét.\nVui lòng kiểm tra lại',
    'fraud_warning_1': 'CẢNH BÁO GIAN LẬN:\nBạn đang cách người bán',
    'fraud_warning_2': 'm.\nVui lòng đứng gần nhau để xác nhận',
    'login_required_action': 'Vui lòng đăng nhập để thực hiện',
    'transaction_success_title': 'Giao dịch thành công!',
    'transaction_success_detail':
        'Hệ thống đã xác nhận hai bạn đang ở gần nhau. Người bán đã nhận được 10 điểm tích lũy',
    'camera_error_title': 'Không mở được Camera!',
    'camera_perm_hint':
        'Hãy vào Cài đặt -> Ứng dụng -> DanaNet -> Quyền -> Bật Camera',
    'retry': 'Thử lại',
    'notification': 'Thông báo',
    'camera_not_found': 'Không tìm thấy camera!',
    'camera_error': 'Lỗi camera',
    'capture_id_card': 'Chụp ảnh CCCD',
    'place_id_card': 'Đặt CCCD nằm gọn trong khung',
    'qr_expired':
        'Mã QR đã hết hạn (Quá 5 phút). Vui lòng yêu cầu người bán tạo mã mới.',
    'transaction_already_completed':
        'Giao dịch này ĐÃ ĐƯỢC THỰC HIỆN trước đó!\nBạn không thể quét lại.',
    'post_completed_error': 'Bài viết đã hoàn thành giao dịch.',
    'close': 'Đóng',
    'qr_validity_warning': '(Mã này chỉ có hiệu lực trong 5 phút)',
    'gemini_classify_prompt':
        'Nhìn vào ảnh này và xác định đây là loại rác gì? (Ví dụ: Nhựa, Giấy, Kim loại, Hữu cơ, hay Vô cơ). Trả lời ngắn gọn tên loại rác.',
    'low_confidence_switch': 'Độ tin cậy thấp, đang hỏi lại AI...',
  };

  static final Map<String, String> _english = {
    'app_name': 'DanaNet',
    'ask_ai': 'Ask AI Assistant',
    'tree_grew': 'The tree has grown! 🌱 ➔ 🌿',
    'need_water': 'Need 20 💧 to water.',
    'reset_title': 'Rebirth Tree? ♻️',
    'reset_content': 'Do you want to plant a new tree?',
    'cancel': 'Cancel',
    'confirm': 'Confirm',
    'max_level_title': 'Max Level Reached! 👑',
    'great': 'Awesome',
    'default_result': 'Take a photo for classification',
    'uploading': 'Uploading to Server...',
    'result_prefix': 'Result:',
    'confidence': 'Confidence:',
    'server_error': 'Server Error:',
    'connection_error': 'Connection Error',
    'understood': 'Understood',
    'analysis_result': 'Analysis Result',
    'unknown': 'Unknown',
    'profile': 'Profile',
    'dark_mode': 'Dark Mode',
    'report_trash': 'Report Trash',
    'report_history': 'Report History',
    'forum': 'Scrap Forum',
    'redeem_points': 'Redeem Points',
    'feedback': 'Send Feedback',
    'about_app': 'About App',
    'change_password': 'Change Password',
    'logout': 'Logout',
    'logout_confirm_title': 'Logout',
    'logout_confirm_msg': 'Are you sure you want to logout?',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_new_password': 'Confirm New Password',
    'forgot_password_q': 'Forgot current password?',
    'save_changes': 'Save Changes',
    'enter_old_pass': 'Please enter old password',
    'pass_min_len': 'Password must be 6+ chars',
    'pass_not_match': 'Passwords do not match',
    'pass_change_success': 'Password changed successfully!',
    'email_sent': 'Reset email sent to',
    'error': 'Error',
    'ai_scan_title': 'AI Waste Classification (Server)',
    'sending_server': 'Sending to Server...',
    'take_trash_photo': 'Take a trash photo',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'your_garden': 'Your Garden',
    'level_max': 'Level: MAX 👑',
    'level': 'Level:',
    'rebirth_tree': 'Rebirth Tree',
    'water_tree': 'Water Tree (-20💧)',
    'ai_bot_name': 'BlueBot Assistant',
    'ai_input_hint': 'Please enter your question',
    'ai_system_busy':
        'All systems are busy or overloaded. Please try again in a few minutes!',
    'ai_persona':
        'You are an environmental and waste management expert named BlueBot. Your task is to guide users on how to sort waste, recycle, and handle hazardous waste. Please answer concisely, in a friendly manner, and use emojis. If the user asks about topics unrelated to waste or the environment, politely refuse.',
    'ai_greeting':
        'Hello! 🌊 I am BlueBot. Wondering where to throw this trash? Just ask me!',
    'profile_title': 'User Profile',
    'verified': 'Verified',
    'pending_approval': 'Pending Approval',
    'verify_now': 'Verify Now (Not verified)',
    'basic_info': 'Basic Information',
    'full_name': 'Full Name',
    'enter_name': 'Enter name',
    'email': 'Email',
    'phone_number': 'Phone Number',
    'activity_address': 'Activity Address',
    'search_help': 'Search by Province/District/Ward',
    'province_city': 'Province/City',
    'district': 'District',
    'ward': 'Ward',
    'street_name': 'Street Name, House No.',
    'enter_street': 'Please enter street name',
    'select_province': 'Please select Province',
    'select_district': 'Please select District',
    'select_ward': 'Please select Ward',
    'kyc_title': 'Identity Verification (eKYC)',
    'kyc_desc': 'Please upload ID card photos to verify',
    'front_card': 'Front Side',
    'back_card': 'Back Side',
    'send_request': 'SEND REQUEST',
    'take_photo': 'Take Photo',
    'choose_gallery': 'Choose from Gallery',
    'update_success': 'Update successful!',
    'report_title': 'Report Trash Point',
    'scene_image': '1. Scene Image:',
    'tap_to_capture': 'Tap to capture',
    'ai_checking': 'AI is checking fill level...',
    'ai_assessment': 'AI Assessment:',
    'location_section': '2. Location:',
    'search_province': 'Search Province/City',
    'search_district': 'Search District',
    'search_ward': 'Search Ward',
    'street_hint': 'Street name, house no.',
    'content_section': '3. Content:',
    'desc_hint': 'Description',
    'emergency_report': 'EMERGENCY REPORT',
    'send_report': 'SEND REPORT',
    'fill_info_alert': 'Please fill in all information!',
    'report_success': 'Report sent successfully!',
    'ai_error_overload':
        'System overloaded. Please try again later or enter description manually',
    'ai_error': 'Image processing error',
    'ai_prompt':
        'Act as an environmental assistant. Look at the image and give a short feedback to the user:\n'
            '- What is this? (Bin, dump site, or other object?)\n'
            '- How is the sanitation? (Clean, messy, or overflowing?)\n'
            'At the end, MUST include a conclusion in brackets: [NORMAL] or [EMERGENCY] (Only choose Emergency if the bin is >90% full or trash is scattered polluting the area).\n'
            'Desired output example: "This is just a wooden chair, not a trash site. The area is clean. [NORMAL]"',
    'history_title': 'Report History',
    'login_required': 'Please login',
    'load_err': 'Error loading data',
    'no_reports': 'You have not sent any reports.',
    'processed': 'PROCESSED',
    'pending': 'PENDING',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm_delete': 'Confirm Delete',
    'delete_msg': 'Are you sure you want to delete this report?',
    'deleted': 'Report deleted',
    'delete_err': 'Delete error',
    'update_info': 'Update Information',
    'content_desc': 'Description content',
    'enter_new_content': 'Enter new content',
    'please_fill': 'Please do not leave information empty',
    'update_err': 'Update error',
    'redeem_title': 'Redeem Gifts & Vouchers',
    'your_points': 'Your Accumulated Points',
    'earn_points_hint': 'Sell scrap to earn points!',
    'no_rewards': 'No rewards available',
    'gift_default': 'Gift',
    'points': 'points',
    'redeem_now_btn': 'REDEEM NOW',
    'not_enough_points_btn': 'NOT ENOUGH POINTS',
    'not_enough_points_msg': 'Not enough points!',
    'confirm_redeem': 'Confirm Redemption',
    'redeem_ask_1': 'Do you want to use',
    'redeem_ask_2': 'points to redeem',
    'redeem_now': 'Redeem Now',
    'insufficient_points_err':
        'Insufficient points (might have changed elsewhere)',
    'redeem_success_title': 'Redemption Successful!',
    'redeem_success_msg_1': 'You have successfully redeemed',
    'redeem_success_msg_2': 'Redeemed successfully',
    'support_info_title': 'Support Information',
    'important_note': 'Important Notice:',
    'support_desc':
        'If you do not receive the gift within 2-3 days, please contact:\n\n📞 Hotline: 0907160203\n🏠 Address: K55/28 Ngu Hanh Son, Da Nang\n\nfor immediate assistance.',
    'sync_success': 'Synced! Actual points:',
    'sync_error': 'Sync error:',
    'feedback_title': 'Send Feedback',
    'enter_feedback_err': 'Please enter your feedback!',
    'anonymous': 'Anonymous',
    'feedback_success': 'Thank you for your feedback!',
    'how_feel': 'How do you feel about the app?',
    'rate_hint': 'Select stars to rate',
    'feedback_content': 'Feedback content:',
    'feedback_hint_text': 'Please share your thoughts to help us improve',
    'send_feedback_btn': 'SEND FEEDBACK',
    'app_version': 'Version',
    'intro_header': '📖 Introduction',
    'intro_content':
        'DanaNet is a community app promoting waste sorting and environmental protection. \n\nWe help scrap owners easily connect with collectors while earning points for attractive rewards.',
    'usage_header': '🚀 How to use',
    'step1_title': 'Post Scrap for Sale',
    'step1_desc': 'Take photos, enter details, and select your location',
    'step2_title': 'AI Analysis',
    'step2_desc': 'AI system assists in identifying waste types',
    'step3_title': 'Trade & Scan QR',
    'step3_desc': 'Meet the buyer and scan QR code to confirm transaction',
    'step4_title': 'Earn Points & Redeem',
    'step4_desc': 'Receive reward points and exchange for vouchers or gifts',
    'dev_team': '💻 Development Team',
    'dev_role': 'Developer & Founder',
    'copyright': '© 2025 DanaNet Project by Nguyen Ky Nam',
    'app_welcome': 'WELCOME TO DANANET',
    'app_slogan': 'Join hands to protect the environment',
    'login_title': 'LOGIN',
    'register_title': 'REGISTER ACCOUNT',
    'email_or_phone': 'Email or Phone Number',
    'password': 'Password',
    'otp_hint': 'System will send OTP for verification',
    'forgot_password': 'Forgot password?',
    'register_now': 'REGISTER NOW',
    'send_otp': 'SEND OTP',
    'login_now': 'LOGIN',
    'have_account': 'Have an account? Back to Login',
    'no_account': 'No account? Register via Email',
    'enter_name_err': 'Please enter Full Name!',
    'enter_email_phone_err': 'Please enter Email or Phone!',
    'enter_pass_err': 'Please enter Password!',
    'register_success': 'Registration successful! Entering system...',
    'register_err': 'Registration error:',
    'login_fail': 'Login failed',
    'user_not_found': 'User not found',
    'wrong_password': 'Wrong password',
    'invalid_phone': 'Invalid phone number',
    'auth_error': 'Authentication error',
    'otp_dialog_title': 'Enter OTP',
    'otp_sent_msg': 'Verification code sent to phone',
    'otp_incorrect': 'Incorrect OTP!',
    'new_user': 'New User',
    'account_locked': 'Account has been locked!',
    'enter_email_reset': 'Please enter Email to reset password',
    'reset_email_sent': 'Password reset email sent!',
    'email_not_found': 'Error: Email not found or invalid format',
    'create_post_title': 'Create New Post',
    'edit_post_title': 'Edit Post',
    'forum_rule_info':
        'Forum is strictly for buying/selling scrap and recyclable waste',
    'i_want_sell': 'I want to Sell',
    'i_want_buy': 'I want to Buy',
    'take_photo_required': 'Take Photo (Required)',
    'take_photo_optional': 'Take Photo (Optional)',
    'waste_type_label': 'Waste Type',
    'post_title_label': 'Title',
    'enter_title_err': 'Please enter title',
    'post_desc_label': 'Detailed description',
    'address_contact_header': 'Address & Contact',
    'contact_phone': 'Contact Phone',
    'enter_phone_err': 'Please enter Phone Number',
    'policy_pledge':
        'I pledge this post is relevant and I take responsibility for the info',
    'post_now_btn': 'POST NOW',
    'update_post_btn': 'UPDATE POST',
    'full_address_err': 'Please select full address!',
    'seller_image_err': 'Sellers must provide a product photo!',
    'policy_err': 'Please agree to the policy!',
    'post_success': 'Post created successfully!',
    'post_update_success': 'Post updated successfully!',
    'type_paper': 'Paper & Cardboard',
    'type_plastic': 'Recycled Plastic',
    'type_metal': 'Metal (Iron/Alum)',
    'type_electronic': 'Old Electronics',
    'type_glass': 'Glass',
    'type_other': 'Other Scrap',
    'anonymous_user': 'Anonymous',
    'other_waste': 'Other',
    'buy_prefix': 'Buying: ',
    'sell_prefix': 'Selling: ',
    'just_now': 'Just now',
    'recently': 'Recently',
    'no_address': 'No address',
    'transaction_completed': 'COMPLETED',
    'forum_title': 'Online Scrap Market',
    'filter_area': 'Filter by Area',
    'clear_filter': 'Clear Filter',
    'apply': 'Apply',
    'area_label': 'Area:',
    'filter_all': 'All',
    'filter_seller': 'Seller',
    'filter_buyer': 'Buyer',
    'post_btn': 'Post Ad',
    'no_posts': 'No posts yet',
    'no_posts_match': 'No matching posts found',
    'post_detail_title': 'Post Details',
    'enable_gps_err': 'Please enable GPS to continue',
    'gps_denied_err': 'Location permission denied',
    'gps_permanent_denied_err':
        'Location permission permanently denied. Please check settings',
    'transaction_success_msg': 'Transaction successful! Points added',
    'qr_auth_title': 'Transaction Verification Code',
    'qr_instruction': 'Show this code to Buyer.\nMax allowed distance: 15m',
    'waiting_buyer_scan': 'Waiting for buyer to scan...',
    'undo_title': 'Undo Transaction?',
    'undo_msg': 'Awarded points will be revoked. Are you sure?',
    'agree_undo': 'Confirm Undo',
    'undo_success': 'Undone and points revoked.',
    'report_post_title': 'Report Post',
    'select_reason_label': 'Select reason:',
    'report_detail_hint': 'Additional details (Optional)',
    'send_report_btn': 'Send Report',
    'report_thank_you': 'Report sent. Thank you!',
    'login_to_report': 'Please login to report!',
    'delete_post_confirm': 'Delete Post?',
    'action_cannot_undo': 'This action cannot be undone',
    'delete_post_success': 'Post deleted',
    'post_deleted_or_missing': 'Post no longer exists',
    'undo_transaction_btn': 'UNDO TRANSACTION',
    'show_qr_btn': 'SHOW TRANSACTION QR',
    'call_btn': 'CALL',
    'scan_qr_btn': 'SCAN QR',
    'transaction_done_btn': 'COMPLETED',
    'edit_post_menu': 'Edit',
    'delete_post_menu': 'Delete Post',
    'report_violation_menu': 'Report Violation',
    'image_error': 'Image Error',
    'transaction_completed_banner': 'TRANSACTION COMPLETED',
    'want_to_sell_tag': 'Selling',
    'want_to_buy_tag': 'Buying',
    'description_header': 'Description:',
    'no_description': 'No description',
    'reason_scam': 'Scam/Fraud',
    'reason_prohibited': 'Prohibited Items',
    'reason_spam': 'Spam/Advertising',
    'reason_hate': 'Hate Speech',
    'reason_other': 'Other',
    'scan_confirm_title': 'Scan Verification Code',
    'qr_invalid': 'Invalid QR Code',
    'qr_missing_info': 'QR Code missing required info',
    'qr_wrong_post':
        'Wrong QR Code!\nYou are viewing a different post.\nPlease check again',
    'fraud_warning_1': 'FRAUD WARNING:\nYou are',
    'fraud_warning_2': 'm away from seller.\nPlease stand closer to confirm',
    'login_required_action': 'Please login to perform this action',
    'transaction_success_title': 'Transaction Successful!',
    'transaction_success_detail':
        'System confirmed proximity. Seller received 10 points.',
    'camera_error_title': 'Cannot open Camera!',
    'camera_perm_hint':
        'Go to Settings -> Apps -> DanaNet -> Permissions -> Enable Camera',
    'retry': 'Retry',
    'notification': 'Notification',
    'camera_not_found': 'No camera found!',
    'camera_error': 'Camera error',
    'capture_id_card': 'Capture ID Card',
    'place_id_card': 'Place ID card within the frame',
    'qr_expired':
        'QR code expired (Over 5 minutes). Please request seller to generate new code.',
    'transaction_already_completed':
        'This transaction is ALREADY COMPLETED!\nYou cannot scan again.',
    'post_completed_error': 'Post transaction completed.',
    'close': 'Close',
    'qr_validity_warning': '(This code is valid for 5 minutes only)',
    'gemini_classify_prompt':
        'Identify this waste item. Is it Recyclable (Plastic, Paper, Metal), Organic, or Inorganic? Answer concisely with just the category.',
    'low_confidence_switch': 'Low confidence, asking AI...',
  };
}