// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2AHnsIp62P_wnJaPfAMOUwP-zE8oApO8',
    appId: '1:443342136092:web:128ebb88e217e3f95e50d9',
    messagingSenderId: '443342136092',
    projectId: 'garbage-8e4be',
    authDomain: 'garbage-8e4be.firebaseapp.com',
    storageBucket: 'garbage-8e4be.firebasestorage.app',
    measurementId: 'G-Z99VLM2NBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYYvVvI1Zp3cY00o8JCxxu2sEgciV4GP4',
    appId: '1:443342136092:android:4290d2b12e5295615e50d9',
    messagingSenderId: '443342136092',
    projectId: 'garbage-8e4be',
    storageBucket: 'garbage-8e4be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcstWPn-6X8UAQ2DVPXEMk700NpL5XTQc',
    appId: '1:443342136092:ios:bfd28f8ac1848fc95e50d9',
    messagingSenderId: '443342136092',
    projectId: 'garbage-8e4be',
    storageBucket: 'garbage-8e4be.firebasestorage.app',
    iosBundleId: 'com.example.ck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcstWPn-6X8UAQ2DVPXEMk700NpL5XTQc',
    appId: '1:443342136092:ios:bfd28f8ac1848fc95e50d9',
    messagingSenderId: '443342136092',
    projectId: 'garbage-8e4be',
    storageBucket: 'garbage-8e4be.firebasestorage.app',
    iosBundleId: 'com.example.ck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2AHnsIp62P_wnJaPfAMOUwP-zE8oApO8',
    appId: '1:443342136092:web:5933f65dc7b38c0f5e50d9',
    messagingSenderId: '443342136092',
    projectId: 'garbage-8e4be',
    authDomain: 'garbage-8e4be.firebaseapp.com',
    storageBucket: 'garbage-8e4be.firebasestorage.app',
    measurementId: 'G-6E4R5H6SST',
  );
}
